config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :posts, param: :uuid do
      member do
        put :publish
        put :unpublish
      end
    end
  end

  scope ':channel' do
    resources :posts, only: [:show, :index], param: :uuid
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  before_validation :check_uuid
  validates :uuid, uniqueness: true, presence: true

  scope :of_channel, -> (channel) { where(channel: channel) }
  scope :published, -> { where.not(published_at: nil) }
  scope :incremental, -> { order(published_at: :desc) }

  def publish!
    update published_at: Time.zone.now
  end

  def unpublish!
    update published_at: nil
  end

  private

  def check_uuid
    return unless self.uuid.nil?
    uuid  = SecureRandom.uuid
    while self.class.where(uuid: uuid).count > 0
      uuid = SecureRandom.uuid
    end
    self.uuid = uuid
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]
  def index
    @posts = Post.incremental
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create post_params
    show_post
  end

  def edit
  end

  def update
    @post = Post.update post_params
    show_post
  end

  def destroy
    @post.destroy
  end

  def publish
    @post.publish!
    show_post
  end

  def unpublish
    @post.unpublish!
    show_post
  end

  private

  def show_post
    redirect_to admin_post_path uuid: @post.uuid and return
  end

  def post_params
    params.require(:post).permit(:title, :message, :channel, :url)
  end

  def set_post
    @post = Post.find_by_uuid params[:uuid]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.of_channel(params[:channel]).published.incremental
  end

  def show
    @post = Post.of_channel(params[:channel]).published.find_by_uuid params[:uuid]
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, post] do |p| %>
  <%= p.label :channel %>
  <%= p.text_field :channel %> <br />
  <%= p.label :title %>
  <%= p.text_field :title %> <br />
  <%= p.label :message %>
  <%= p.text_area :message %> <br />
  <%= p.label :url %>
  <%= p.text_field :url %> <br />
  <%= submit_tag  %>
<% end %>

app/views/admin/posts/_post.html.erb
<li class="nms-post-list-item">
  <%= link_to admin_post_path(uuid: post.uuid) do %>
    <%= post.title %>
  <% end %>
</li>

app/views/admin/posts/edit.html.erb
<%= render partial: "form", locals: {post: @post} %>

<ul class="nms-edit-post-options">
  <li><%= link_to 'Back',  admin_post_path(uuid: @post.uuid) %></li>
  <li><%= link_to 'All posts', admin_posts_path %></li>
</ul>

app/views/admin/posts/index.html.erb
<h1>Posts</h1>
<ul class="nms-post-list">
  <%= render partial: "post", collection: @posts %>
</ul>
<ul class="nms-posts-actions">
  <li><%= link_to "New post", new_admin_post_path %></li>
</ul>

app/views/admin/posts/new.html.erb
<%= render partial: "form", locals: {post: Post.new } %>

<ul class="nms-new-post-options">
  <li><%= link_to 'Back', admin_posts_path %></li>
</ul>

app/views/admin/posts/show.html.erb
<article class="nms-post" data-uuid="<%= @post.uuid %>">
  <h1 class="nms-post-title"><%= @post.title %></h1>
  <p class="nms-post-header">
    <small class="nms-post-channel" data-value="<%= @post.channel %>">Channel: <%= @post.channel %></small>
    <% if @post.published_at %>
    <br />
    <small class="nms-post-publication-date" data-value="<%= @post.published_at %>">Published: <%= l @post.published_at %></small>
    <% end %>
  </p>
  <p class="nms-post-message"><%= @post.message %></p>
</article>
<ul class="nms-post-actions">
  <li><%= link_to 'Edit', edit_admin_post_path(uuid: @post.uuid) %></li>
  <% if @post.published_at.nil? %>
    <li><%= link_to 'Publish', publish_admin_post_path(uuid: @post.uuid), method: :put %></li>
  <% else %>
    <li><%= link_to 'Unpublish', unpublish_admin_post_path(uuid: @post.uuid), method: :put %></li>
  <% end %>
  <li><%= link_to 'All posts', admin_posts_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<li class="nms-post-list-item">
  <%= link_to post_path(uuid: post.uuid,channel: post.channel) do %>
    <%= post.title %>
  <% end %>
</li>

app/views/posts/index.html.erb
<h1><%= params[:channel] %></h1>
<ul class="nms-post-list">
  <%= render partial: "post", collection: @posts %>
</ul>

app/views/posts/show.html.erb
<article class="nms-post" data-uuid="<%= @post.uuid %>">
  <h1 class="nms-post-title"><%= @post.title %></h1>
  <p class="nms-post-header">
    <small class="nms-post-publication-date" data-value="<%= @post.published_at %>"><%= l @post.published_at %></small>
  </p>
  <p class="nms-post-message"><%= @post.message %></p>

</article>